### ISSUE TITLE
Failed - Building from source

### ISSUE THREAD

**Issue by ramirocorletti** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#129]
When completing steps under building from source: https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#building-from-source

We get the following error:

> Configure project :import
Evaluating project ':import' using build file 'C:\healthcare-dicom-dicomweb-adapter-master\import\build.gradle'.
Adding license extension
Adding download licenses extension
Applying defaults to download task: :import:downloadLicenses
Adding licenseMain task for sourceSet main
Applying license defaults to task: :import:licenseMain
Applying license defaults to task: :import:licenseFormatMain
Adding licenseTest task for sourceSet test
Applying license defaults to task: :import:licenseTest
Applying license defaults to task: :import:licenseFormatTest
Default docker.url set to tcp://127.0.0.1:2375
Applying defaults to download task: :import:downloadOpensSourceLicenses
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/com/github/jai-imageio/jai-imageio-jpeg2000/1.3.1-dicomadapter/jai-imageio-jpeg2000-1.3.1-dicomadapter.pom]
Resource missing. [HTTP GET: https://www.dcm4che.org/maven2/com/github/jai-imageio/jai-imageio-jpeg2000/1.3.1-dicomadapter/jai-imageio-jpeg2000-1.3.1-dicomadapter.pom]
Resource missing. [HTTP GET: https://jitpack.io/com/github/jai-imageio/jai-imageio-jpeg2000/1.3.1-dicomadapter/jai-imageio-jpeg2000-1.3.1-dicomadapter.pom]
All projects evaluated.

FAILURE: Build failed with an exception.

* What went wrong:
Project '.args=--dimse_aet=IMPORTADAPTER --dimse_port=4008 --dicomweb_address=https' not found in root project 'healthcare-dicom-dicomweb-adapter-master'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s

**Comment by danielbeaudreau** [comment]
Sometimes fetching the dependencies is flaky because the build script downloads them from the internet. Could you please retry?

**Comment by ramirocorletti** [comment]
Thanks @danielbeaudreau for your response. I retried several times and the error persists. I belive it might have something to do with the syntax:

What went wrong:
Project '.args=--dimse_aet=IMPORTADAPTER --dimse_port=4008 --dicomweb_address=https' not found in root project 'healthcare-dicom-dicomweb-adapter-master'.

**Comment by danielbeaudreau** [comment]
What version of gradle are you using? 
Can you try running just "gradle build"
https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#building-from-source

**Comment by ramirocorletti** [comment]
Gradle build builds succesfuly

---------------------------------

PS C:\healthcare-dicom-dicomweb-adapter-master\import> gradle build
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 24s
21 actionable tasks: 1 executed, 20 up-to-date

-----------------------------------
PS C:\healthcare-dicom-dicomweb-adapter-master\import> gradle -v

------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (AdoptOpenJDK 11.0.10+9)
OS:           Windows 10 10.0 amd64
-----------------------------------

**Comment by danielbeaudreau** [comment]
Could you paste the failing command please?

**Comment by ramirocorletti** [comment]
PS C:\healthcare-dicom-dicomweb-adapter-master\import> gradle run -Dorg.args="--dimse_aet=IMPORTADAPTER --dimse_port=4008 --dicomweb_address=https://healthcare.googleapis.com/v1/projects/xxxxx/locations/xxxxx/datasets/xxxxx/dicomStores/xxxxx/dicomWeb"

**Comment by danielbeaudreau** [comment]
Could you try Dexec.args instead of Dorg.args?

**Comment by ramirocorletti** [comment]
Yes, sorry, I am using Decec.args not Dorg, the previous message was a typo from another test, the command line I am using is:

PS C:\healthcare-dicom-dicomweb-adapter-master\import> gradle run -Dexec.args="--dimse_aet=IMPORTADAPTER --dimse_port=4008 --dicomweb_address=https://healthcare.googleapis.com/v1/projects/xxxxx/locations/xxxxx/datasets/xxxxx/dicomStores/xxxxx/dicomWeb"

**Comment by danielbeaudreau** [comment]
I ran gradle run -Dexec.args="--dimse_aet=IMPORTADAPTER --dimse_port=4008 --dicomweb_address=http://localhost:80" 
in the import directory and it worked for me, it must be something with your environment. I wonder if it is due to running on Windows?

Could you try running gradle clean and then running the command again?

**Comment by danielbeaudreau** [comment]
If that does not work could you run with  --stacktrace option and paste the output?

**Comment by ramirocorletti** [comment]
If it works for you might be something within my environment. Below find the stacktrace output in case something comes up. If not I can build a linux env and retry:

PS C:\healthcare-dicom-dicomweb-adapter-master\import> gradle run -Dexec.args="--dimse_aet=IMPORTADAPTER --dimse_port=4008 --dicomweb_address=https://healthcare.googleapis.com/v1/projects/xxxxx/locations/xxxxx/datasets/xxxx/dicomStores/xxxxx/dicomWeb" --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Project '.args=--dimse_aet=IMPORTADAPTER --dimse_port=4008 --dicomweb_address=https' not found in project ':import'.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.execution.taskpath.ProjectFinderByTaskPath$ProjectLookupException: Project '.args=--dimse_aet=IMPORTADAPTER --dimse_port=4008 --dicomweb_address=https' not found in project ':import'.
        at org.gradle.execution.taskpath.ProjectFinderByTaskPath.findProject(ProjectFinderByTaskPath.java:47)
        at org.gradle.execution.taskpath.TaskPathResolver.resolvePath(TaskPathResolver.java:49)
        at org.gradle.execution.DefaultTaskSelector.getSelection(DefaultTaskSelector.java:92)
        at org.gradle.execution.DefaultTaskSelector.getSelection(DefaultTaskSelector.java:78)
        at org.gradle.execution.CompositeAwareTaskSelector.getSelection(CompositeAwareTaskSelector.java:93)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:43)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:46)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:55)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:26)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:63)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:45)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:55)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:26)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:63)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:55)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.lambda$select$0(DefaultBuildConfigurationActionExecuter.java:42)
        at org.gradle.internal.Factories$1.create(Factories.java:31)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry.withMutableStateOfAllProjects(DefaultProjectStateRegistry.java:141)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry.withMutableStateOfAllProjects(DefaultProjectStateRegistry.java:128)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:40)
        at org.gradle.initialization.DefaultTaskExecutionPreparer.prepareForTaskExecution(DefaultTaskExecutionPreparer.java:38)
        at org.gradle.initialization.BuildOperationFiringTaskExecutionPreparer$CalculateTaskGraph.populateTaskGraph(BuildOperationFiringTaskExecutionPreparer.java:117)
        at org.gradle.initialization.BuildOperationFiringTaskExecutionPreparer$CalculateTaskGraph.run(BuildOperationFiringTaskExecutionPreparer.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
        at org.gradle.initialization.BuildOperationFiringTaskExecutionPreparer.prepareForTaskExecution(BuildOperationFiringTaskExecutionPreparer.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.prepareTaskExecution(DefaultGradleLauncher.java:233)
        at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:167)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:148)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
        at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:72)
        at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:67)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:213)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:67)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:56)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:77)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.lambda$execute$0(InProcessBuildActionExecuter.java:54)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:53)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
        at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.lambda$execute$0(BuildTreeScopeLifecycleBuildActionExecuter.java:33)
        at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:49)
        at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:32)
        at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:27)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:104)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:64)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.lambda$execute$0(SessionScopeLifecycleBuildActionExecuter.java:54)
        at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:67)
        at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:50)
        at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s

**Comment by danielbeaudreau** [comment]
Seems like gradle is searching for the args as the task, but it should know that "run" is the desired task to execute.
Could you try on linux and see if that works?

**Comment by maxirodr** [comment]
Hello @danielbeaudreau, we're trying with @ramirocorletti to run the build now from Ubuntu 18.04, and it's impossible for me to run the build:

![imagen](https://user-images.githubusercontent.com/25252671/115597949-3ca01500-a2b0-11eb-9520-37133af06dcc.png)

with this dependencies:

![imagen](https://user-images.githubusercontent.com/25252671/115598039-5b061080-a2b0-11eb-9dad-09151783e994.png)

**Comment by danielbeaudreau** [comment]
Please use an older version of gradle below 7. Gradle made some breaking changes in v7 that broke our build.

**Comment by maxirodr** [comment]
Working perfect with Gradle 6.6, in Ubuntu 18.04 with latests releases (java, sdk, etc). Maybe need to detail about Gradle 6.6 as prefered version in the building of the repo (locally). Thanks for the help @danielbeaudreau

**Comment by danielbeaudreau** [comment]
Glad it worked. If I get some time, would like to fix the build to work with both v7 and v6.

**Comment by maxirodr** [comment]
@danielbeaudreau Daniel, sorry i bother you again. I don't know what are the scopes I need to select in GCP to let me storage into it:

![imagen](https://user-images.githubusercontent.com/25252671/115747352-91549600-a36b-11eb-81eb-34e20172a76f.png)

i'm trying to send DCM file from SCU Emulator to the Adapter:

![imagen](https://user-images.githubusercontent.com/25252671/115747148-581c2600-a36b-11eb-95aa-9824c6a11d85.png)

**Comment by danielbeaudreau** [comment]
Could you try specifying the flag 
```
--oauth_scopes=https://www.googleapis.com/auth/cloud-platform
```

**Comment by maxirodr** [comment]
@danielbeaudreau Daniel, perfect. I've added the remaining params to make it work to IAM (GCP) using the same credentials and now it work perfect. The adapter is forwarding the DCM files. Just one thing is showing now and I don't know about what is referring to:

![imagen](https://user-images.githubusercontent.com/25252671/115786450-1ddd7380-a3c1-11eb-9db7-d16990613769.png)


Anyway, is working.

**Comment by maxirodr** [comment]
@danielbeaudreau hello Daniel, how are you? We're trying now to run the same in Windows 10. I've setup the same dependencies in Linux and we've some troubles to run. "gradle build" works okay, and have built without problems, the problem is the other command, to run the adapter:

![gradle_1](https://user-images.githubusercontent.com/25252671/116082260-7d76a000-a69b-11eb-9bab-374ed0711b60.png)


![gradle_2](https://user-images.githubusercontent.com/25252671/116082268-80719080-a69b-11eb-9961-85af17e8c23e.png)


![gradle_3](https://user-images.githubusercontent.com/25252671/116082277-836c8100-a69b-11eb-894d-ee696f2ab1bb.png)

**Comment by danielbeaudreau** [comment]
Hi Max, re: the warnings, you may ignore those.

This looks like a bug. I believe the adapter cannot run on Windows at the moment, there seems to be a compatibility bug with the Gradle setup and windows.

**Comment by maxirodr** [comment]
@danielbeaudreau thank you for the answer :(

so for now this thread is closed. Thanks!

**Comment by maxirodr** [comment]
@danielbeaudreau if is it possible to talk with you outside here (because i've a few questions more), reach me at: https://privnote.com/JwsLJwcI#8OP44hB0v

thanks!

**Comment by danielbeaudreau** [comment]
Hi, if you have any other questions, you could ask them in this bug
