### ISSUE TITLE
C-MOVE fails with SOP Class not supported

### ISSUE THREAD

**Issue by akash769** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#169]
I am trying to execute `movescu` command, i have configured AETs.json file using the caller AET, and corresponding details, but i get SOP Class not supported error.

AETs.json
```
[{
"name": "CALLERAET",
"ip": "172.16.0.2"
"port": "2575"
}]
```

running the command,
`movescu 10.10.2.3 2575 -aec IMPORTADAPTER -aet CALLERAET tesfile.dcm`

Gives below output,
```
D: DcmDataset::read() TransferSyntax="Little Endian Implicit"
W: Move response with error status (Refused: SOPClassNotSupported)
I: Received Final Move Response
D: ===================== INCOMING DIMSE MESSAGE ====================
D: Message Type                  : C-MOVE RSP
D: Message ID Being Responded To : 1
D: Affected SOP Class UID        : none
D: Remaining Suboperations       : none
D: Completed Suboperations       : none
D: Failed Suboperations          : none
D: Warning Suboperations         : none
D: Data Set                      : none
D: DIMSE Status                  : 0x0122: Refused: SOP Class not supported
D: ======================= END DIMSE MESSAGE =======================
I: Releasing Association
```

Adapter logs,
```
DEBUG org.dcm4che3.net.Dimse  - IMPORTADAPTER<-CALLERAET(1) >> 1:C-MOVE-RQ Dataset receiving...
INFO  org.dcm4che3.net.Association  - IMPORTADAPTER<-CALLERAET(1): processing 1:C-MOVE-RQ[pcid=3, prior=0, dest=CALLERAET
  cuid=1.2.840.10008.5.1.4.1.2.1.2 - Patient Root Query/Retrieve Information Model - MOVE
  tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian] failed. Caused by:
org.dcm4che3.net.service.DicomServiceException
        at org.dcm4che3.net.service.DicomServiceRegistry.lookupService(DicomServiceRegistry.java:137)
        at org.dcm4che3.net.service.DicomServiceRegistry.onDimseRQ(DicomServiceRegistry.java:86)
        at org.dcm4che3.net.ApplicationEntity.onDimseRQ(ApplicationEntity.java:491)
        at org.dcm4che3.net.Association.onDimseRQ(Association.java:750)
        at org.dcm4che3.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:467)
        at org.dcm4che3.net.Association.handlePDataTF(Association.java:733)
        at org.dcm4che3.net.State$4.onPDataTF(State.java:108)
        at org.dcm4che3.net.Association.onPDataTF(Association.java:729)
        at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:177)
        at org.dcm4che3.net.Association$2.run(Association.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
INFO  org.dcm4che3.net.Dimse  - IMPORTADAPTER<-CALLERAET(1) << 1:C-MOVE-RSP[pcid=3, status=122H
  tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian]
DEBUG org.dcm4che3.net.Dimse  - IMPORTADAPTER<-CALLERAET(1) << 1:C-MOVE-RSP Command:
(0000,0100) US [32801] CommandField
(0000,0120) US [1] MessageIDBeingRespondedTo
(0000,0800) US [257] CommandDataSetType
(0000,0900) US [290] Status
```

Let me know if full logs will help or anything required.

**Comment by jasonklotzer** [comment]
Hi @akash769, can you please share the contents of your `tesfile.dcm`, making sure to remove any PHI? Also what is the SOPClass of the objects you're trying to move?

**Comment by akash769** [comment]
Thanks @jasonklotzer,  I will try to share the testfile, meanwhile, i tried the dcmsend command with the same file and other files and everything did work. if i use orthanc with any of our files, dcmsend and movescu both work. its only movescu + google adapter, i get this error for all the files which we have, not specific to a single file. But i will try and share a demo firle for whcih we got the error
