### ISSUE TITLE
Propagate API Error Message on Store Failure

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#5]
If you bring up the adaptor, but haven't configured the API target properly (e.g. a typo in the name or missing permissions), you'll just get a generic error message when you try and push an image through. Instead, we should return the error message that the API returns.

**Comment by red1408** [comment]
After looking into it: problem is, situation like this fails at low level while sending data stream. There is no http response or http exception involved. I just don't receive a response.

```
org.dcm4che3.net.service.DicomServiceException: java.io.IOException: Error writing request body to server( status = 272 )
	at com.google.cloud.healthcare.imaging.dicomadapter.CStoreService.store(CStoreService.java:84)
	at org.dcm4che3.net.service.BasicCStoreSCP.onDimseRQ(BasicCStoreSCP.java:72)
	at org.dcm4che3.net.service.DicomServiceRegistry.onDimseRQ(DicomServiceRegistry.java:86)
	at org.dcm4che3.net.ApplicationEntity.onDimseRQ(ApplicationEntity.java:485)
	at org.dcm4che3.net.Association.onDimseRQ(Association.java:650)
	at org.dcm4che3.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:459)
	at org.dcm4che3.net.Association.handlePDataTF(Association.java:634)
	at org.dcm4che3.net.State$4.onPDataTF(State.java:103)
	at org.dcm4che3.net.Association.onPDataTF(Association.java:630)
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:177)
	at org.dcm4che3.net.Association$2.run(Association.java:478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.cloud.healthcare.IDicomWebClient$DicomWebException: java.io.IOException: Error writing request body to server
	at com.google.cloud.healthcare.DicomWebClient.stowRs(DicomWebClient.java:128)
	at com.google.cloud.healthcare.imaging.dicomadapter.CStoreService.store(CStoreService.java:75)
	... 13 more
Caused by: java.io.IOException: Error writing request body to server
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3593)
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3576)
	at com.google.api.client.util.ByteStreams.copy(ByteStreams.java:55)
	at com.google.api.client.util.IOUtils.copy(IOUtils.java:94)
	at com.google.api.client.http.AbstractInputStreamContent.writeTo(AbstractInputStreamContent.java:72)
	at com.google.api.client.http.MultipartContent.writeTo(MultipartContent.java:107)
	at com.google.api.client.http.javanet.NetHttpRequest$DefaultOutputWriter.write(NetHttpRequest.java:76)
	at com.google.api.client.http.javanet.NetHttpRequest.writeContentToOutputStream(NetHttpRequest.java:156)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:117)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1011)
	at com.google.cloud.healthcare.DicomWebClient.stowRs(DicomWebClient.java:122)
	... 14 more
```

Unless I'm missing something, this may be a google httpclient bug.

As simple crutch solution, I could use qidors query to test for accessibility before invoking wadors.

**Comment by dzelemba** [comment]
What if we used a different client library? Or what if we just sent raw HTTP requests using Java primitives?

**Comment by red1408** [comment]
After trying different libraries (mostly Apache, and a short attempt with OkHttp).

Apache:
- using InputStream of undetermined length in POST body doesn't quite work (worst of all, it does work like once in 20 attempts) and usually crashes with low level error. So I checked POST with a fixed file, just to see how Apache client reacts to invalid dicomstore or similar errors. Result is about the same as google http client. Low level error without a proper response ( java.net.SocketException: Broken pipe (Write failed) ) .

OkHttp:
- api just doesn't support streams in  POST. I checked out a crutch solution from one of rejected pull-requests, but it didn't work.

It doesn't look like changing client library would help, and seems more likely to introduce extra problems.

**Comment by dzelemba** [comment]
Interesting... is this a Java library issue maybe? Like can you get this to work by just using Java's HTTP packages directly without any client library on top?

Also do you know what HTTP version is being used in all these examples? Maybe forcing them to use HTTP 2.0 will help.

**Comment by red1408** [comment]
Google http client has 2 underlying implementations: HttpURLConnection-based and Apache-based. First is already in use and it doesn't seem like directly using HttpURLConnection would help, unless I actually knew what goes wrong to fix it (in which case it would probably have been a better idea to subclass NetHttpTransport, than implement from zero).
Apache-based has same problem I encountered when using separate Apache http client - "java.net.SocketException: Broken pipe (Write failed)" when working with streams.

As for http2, Google http client doesn't seem to support it.

OkHttp supports http2, but seemingly can't be forced to use it ( https://stackoverflow.com/questions/41925501/java-okhttp3-only-use-http-1-1-or-http-2 ). I have made a few more attempts with and at least got to different errors, but that's about it.

Apache has other libraries to work with http2, but this approach is separate from Apache http client I tried before and more low-level.

**Comment by dzelemba** [comment]
Healthcare API does support http2 you can test with curl. 

What about using HttpURLConnection directly and forcing http2?

**Comment by dzelemba** [comment]
Just to give some background for this issue: it's something that has come up with actual customers and has made debugging this tool very difficult, especially during an active outage where you need to fix the problem as fast as possible. So that's why I'm trying to make sure we really cover all our bases here... this is a major usability issue with this tool right now.

**Comment by red1408** [comment]
I tried native java 11 HTTP client. Not to the point where it can replace original implementation , but at least to POSTing a fixed length file.
Java 11 HTTP client doesn't have multipart content handling and PDVInputStream (dcm4che) being readable only from original thread also conflicts with how java 11 HTTP client works - both are solvable, but there is no point to, unless I can fix the no-response problem.

At least in HTTP2 server does in fact send error response, but for some reason it's DataFrame gets discarded and thus it doesn't appear up the call stack. Took some time debugging internal classes to even get to it. Looking into it further now.

**Comment by dzelemba** [comment]
Nice!
