### ISSUE TITLE
Support in-transit compression for C-STORE -> StowRS

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#56]
Feature request to support a command line parameter that allows a user to configure the adapter such that all instances that pass through C-STORE are compressed before being sent to StowRS.

--store_compress_to_transfer_syntax=<TransferSyntaxUID>

Care should be taken in implementation to minimize the memory overhead required.

To avoid using local disk or having to store large instance fully in memory, no retry behavior will be added in the case of compression failures (which should be very rare).

**Comment by danielbeaudreau** [comment]
To add some more context here:
- To start we only need to support one lossless compression syntax. Dusan and I thought that JPEG2000 will be the best fit, because the healthcare API supports decompressing it easily, and there exists a native Java library for compressing jpeg 2000.
- We don't want to use any C/C++ libraries due to security concerns. We would like to keep the compression libraries java only.
- Here is an open source JPEG 2000 library that you can use: https://jai-imageio.github.io/jai-imageio-jpeg2000/javadoc/com/sun/media/imageioimpl/plugins/jpeg2000/J2KImageReader.html
- You can configure the dcm4che ImageWriterFactory to use this plugin by modifying the properties file in this directory: https://github.com/dcm4che/dcm4che/blob/master/dcm4che-imageio/src/main/java/org/dcm4che3/imageio/codec/ImageWriterFactory.java#L164
The properties file should contain the following config:

1.2.840.10008.1.2.4.90:jpeg2000:com.sun.media.imageioimpl.plugins.jpeg2000.J2KImageWriter::
1.2.840.10008.1.2.4.91:jpeg2000:com.sun.media.imageioimpl.plugins.jpeg2000.J2KImageWriter::

It might be difficult to do this with gradle. 
Please let me know if you have any concerns about the above comments.

**Comment by red1408** [comment]
Overall configuring dcm4che to use the above java lib proved to be fairly easy, but while modifying integration test I run into an issue with it.

Scenario:
1) Original jpeg image is c-stored and transcoded in process to jpeg2k with java lib above, then downloaded (with curl).
2) I c-store jpeg2k image resulting from previous step, adapter is configured to transcode back to jpeg with java lib, and get the below stacktrace. Exactly same c-store command, **but using native opencv lib** passes without problems.

<pre><code>DEBUG org.dcm4che3.imageio.codec.Transcoder  - Decompressor: com.sun.media.imageioimpl.plugins.jpeg2000.J2KImageReader
DEBUG org.dcm4che3.imageio.codec.Transcoder  - Compressor: com.sun.imageio.plugins.jpeg.JPEGImageWriter
INFO  org.dcm4che3.net.Association  - IMPORTADAPTER<-STORESCU(1): processing 1:C-STORE-RQ[pcid=7, prior=0
  cuid=1.2.840.10008.5.1.4.1.1.7 - Secondary Capture Image Storage
  iuid=111 - ?
  tsuid=1.2.840.10008.1.2.4.90 - JPEG 2000 Image Compression (Lossless Only)] failed. Caused by:	
org.dcm4che3.net.service.DicomServiceException: java.lang.RuntimeException: EOF reached before finding Contiguous Codestream Box
	at com.google.cloud.healthcare.imaging.dicomadapter.CStoreService.store(CStoreService.java:149)
	at org.dcm4che3.net.service.BasicCStoreSCP.onDimseRQ(BasicCStoreSCP.java:72)
	at org.dcm4che3.net.service.DicomServiceRegistry.onDimseRQ(DicomServiceRegistry.java:86)
	at org.dcm4che3.net.ApplicationEntity.onDimseRQ(ApplicationEntity.java:474)
	at org.dcm4che3.net.Association.onDimseRQ(Association.java:713)
	at org.dcm4che3.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:467)
	at org.dcm4che3.net.Association.handlePDataTF(Association.java:696)
	at org.dcm4che3.net.State$4.onPDataTF(State.java:103)
	at org.dcm4che3.net.Association.onPDataTF(Association.java:692)
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:177)
	at org.dcm4che3.net.Association$2.run(Association.java:529)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: EOF reached before finding Contiguous Codestream Box
	at com.sun.media.imageioimpl.plugins.jpeg2000.J2KReadState.initializeRead(J2KReadState.java:696)
	at com.sun.media.imageioimpl.plugins.jpeg2000.J2KReadState.<init>(J2KReadState.java:189)
	at com.sun.media.imageioimpl.plugins.jpeg2000.J2KImageReader.read(J2KImageReader.java:446)
	at org.dcm4che3.imageio.codec.Transcoder.decompressFrame(Transcoder.java:600)
	at org.dcm4che3.imageio.codec.Transcoder.compressPixelData(Transcoder.java:475)
	at org.dcm4che3.imageio.codec.Transcoder.processPixelData(Transcoder.java:425)
	at org.dcm4che3.imageio.codec.Transcoder.access$200(Transcoder.java:70)
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:383)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:534)
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:362)
	at com.google.cloud.healthcare.imaging.dicomadapter.CStoreService.lambda$store$1(CStoreService.java:125)
	at com.google.cloud.healthcare.imaging.dicomadapter.CStoreService$StreamCallable.call(CStoreService.java:236)
	at com.google.cloud.healthcare.imaging.dicomadapter.CStoreService$StreamCallable.call(CStoreService.java:220)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
Caused by: java.lang.Error: EOF reached before finding Contiguous Codestream Box
	at jj2000.j2k.fileformat.reader.FileFormatReader.readFileFormat(FileFormatReader.java:289)
	at com.sun.media.imageioimpl.plugins.jpeg2000.J2KReadState.initializeRead(J2KReadState.java:418)
	... 18 more</code></pre>

Looking into it further.

**Comment by red1408** [comment]
Replacing opencv with jai-imageio in dcm2dcm tool and trying to convert jpeg -> jpeg2000 -> jpeg results in the same thing. This isn't adapter issue - jai-imageio can't read what it itself writes.

**Comment by danielbeaudreau** [comment]
Weasis has a compression plugin? Is it java based?

**Comment by red1408** [comment]
Weasis uses it's own implementation of javax.imageio.ImageReader in org.weasis.dicom.codec.DicomMediaIO. But there is no corresponding ImageWriter implementation and it uses opencv internally.

Either way, I think I found what breaks with above scenario.
- Dicom tags have to have even length in bytes. 
- If image encoded in jpeg2000 ends up with odd length, dcm4che adds 1 byte of padding. 
- When decoding pixelData, decoder gets length of incoming data stream as determined by dcm4che (the always even value which can include padding).
- If compressed data is actually of odd length, decoder won't hit exact end of stream due to padding and will try to read next element. Elements ("boxes") start with Int determining their length. But since there is only 1 byte left in stream, trying to read an Int fails.

So, for example, If I use example instance file with frame (all my test were on 1 frame files) which compresses into even length result, this file can be compressed to jpeg2000 and decompressed successfully.

I have an idea of crutch solution - make my own fork of jai imageio, which accepts hitting length - 1 as end of stream (rather than only exact length as it does now). It's only 1 line change.

Of course, I'm open to any better suggestions. Or we could use opencv implementation (which needs native binaries).

**Comment by danielbeaudreau** [comment]
Thanks for the investigation Egor. I'll follow up soon on how we'd like to proceed

**Comment by dzelemba** [comment]
Let's add a wiki entry as the final step here.

**Comment by red1408** [comment]
Added wiki entry https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/wiki/In-transit-transcoding

**Comment by dzelemba** [comment]
Thanks!
